//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteFork.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RemoteFork.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автозапуск.
        /// </summary>
        internal static string Main_Autostart {
            get {
                return ResourceManager.GetString("Main_Autostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет доступа к реестру.
        /// </summary>
        internal static string Main_Can_Not_Access_Registry {
            get {
                return ResourceManager.GetString("Main_Can_Not_Access_Registry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнено скачивание!.
        /// </summary>
        internal static string Main_Download_Completed {
            get {
                return ResourceManager.GetString("Main_Download_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скачивание новой версии.
        /// </summary>
        internal static string Main_Downloading_New_Version {
            get {
                return ResourceManager.GetString("Main_Downloading_New_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включить работу через Proxy.
        /// </summary>
        internal static string Main_Enable_Proxy {
            get {
                return ResourceManager.GetString("Main_Enable_Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка!.
        /// </summary>
        internal static string Main_Error {
            get {
                return ResourceManager.GetString("Main_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный файл плейлиста!.
        /// </summary>
        internal static string Main_Invalid_Playlist_File {
            get {
                return ResourceManager.GetString("Main_Invalid_Playlist_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет активных устройств.
        /// </summary>
        internal static string Main_No_Active_Devices {
            get {
                return ResourceManager.GetString("Main_No_Active_Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string Main_No_Installed_Plugins {
            get {
                return ResourceManager.GetString("Main_No_Installed_Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внешний сервер отключен.
        /// </summary>
        internal static string Main_Server_Disabled {
            get {
                return ResourceManager.GetString("Main_Server_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация сервера.
        /// </summary>
        internal static string Main_ServerRegistration {
            get {
                return ResourceManager.GetString("Main_ServerRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запустите программу от имени администратора!.
        /// </summary>
        internal static string Main_Start_From_Admin_maxi {
            get {
                return ResourceManager.GetString("Main_Start_From_Admin_maxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запустите от администратора!.
        /// </summary>
        internal static string Main_Start_From_Admin_mini {
            get {
                return ResourceManager.GetString("Main_Start_From_Admin_mini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запуск сервера.
        /// </summary>
        internal static string Main_Starting_Server {
            get {
                return ResourceManager.GetString("Main_Starting_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остановка сервера.
        /// </summary>
        internal static string Main_Stopping_Server {
            get {
                return ResourceManager.GetString("Main_Stopping_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на THVP BitTorrent уже запущен!.
        /// </summary>
        internal static string Main_THVP_Already_Running {
            get {
                return ResourceManager.GetString("Main_THVP_Already_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включение не рекомендуется: 
        ///-увеличится время ответа от ForkPlayer к RemoteFork на 20-30сек.
        ///-не будет работать доступ к файлам вашего ПК и плагины
        ///-не будет работать THVP bittorrent
        ///-не будет работать обработка некоторых ресурсов (трее тв, moonwalk).
        /// </summary>
        internal static string Main_TurnOn_Not_Recommended {
            get {
                return ResourceManager.GetString("Main_TurnOn_Not_Recommended", resourceCulture);
            }
        }
    }
}
